"""
Task Management System - Python (Flask) middleware
Connects the HTML/CSS/JS frontend to MySQL.

Run:
    pip install -r requirements.txt
    python app.py
Server starts on http://localhost:5000
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import mysql.connector
import bcrypt

app = Flask(__name__)
CORS(app)  # allow the frontend (served separately) to call this API

# ---------------------------------------------------------------------------
# Database connection settings — edit to match your MySQL setup
# ---------------------------------------------------------------------------
DB_CONFIG = {
    "host": "localhost",
    "user": "root",
    "password": "your_mysql_password",
    "database": "task_management_db",
}


def get_connection():
    return mysql.connector.connect(**DB_CONFIG)


# ---------------------------------------------------------------------------
# LOGIN
# ---------------------------------------------------------------------------
@app.route("/api/login", methods=["POST"])
def login():
    data = request.get_json(force=True)
    username = data.get("username", "").strip()
    password = data.get("password", "")

    if not username or not password:
        return jsonify({"success": False, "message": "Username and password are required."}), 400

    conn = get_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT id, username, password_hash, role FROM users WHERE username = %s", (username,))
    user = cursor.fetchone()
    cursor.close()
    conn.close()

    if not user:
        return jsonify({"success": False, "message": "Invalid username or password."}), 401

    if not bcrypt.checkpw(password.encode("utf-8"), user["password_hash"].encode("utf-8")):
        return jsonify({"success": False, "message": "Invalid username or password."}), 401

    return jsonify({
        "success": True,
        "message": "Login successful.",
        "user": {"id": user["id"], "username": user["username"], "role": user["role"]}
    })


# ---------------------------------------------------------------------------
# TASKS
# ---------------------------------------------------------------------------
@app.route("/api/tasks", methods=["POST"])
def create_task():
    """task_id is auto-generated by MySQL (AUTO_INCREMENT) — never sent by the frontend."""
    data = request.get_json(force=True)
    employee_name = data.get("employee_name", "").strip()
    task_title = data.get("task_title", "")
    completed = data.get("completed", "false")

    if not employee_name:
        return jsonify({"success": False, "message": "Employee name is required."}), 400
    if task_title not in ("task1", "task2", "task3"):
        return jsonify({"success": False, "message": "Invalid task title."}), 400
    if completed not in ("true", "false"):
        return jsonify({"success": False, "message": "Invalid completed value."}), 400

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO tasks (employee_name, task_title, completed) VALUES (%s, %s, %s)",
        (employee_name, task_title, completed)
    )
    conn.commit()
    new_task_id = cursor.lastrowid
    cursor.close()
    conn.close()

    return jsonify({"success": True, "message": "Task saved.", "task_id": new_task_id})


@app.route("/api/tasks", methods=["GET"])
def list_tasks():
    conn = get_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT task_id, employee_name, task_title, completed, created_at FROM tasks ORDER BY task_id DESC")
    rows = cursor.fetchall()
    cursor.close()
    conn.close()
    return jsonify({"success": True, "tasks": rows})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
